[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "node ./dist/server/entry.mjs"

[variables]
NODE_ENV = "production"
PORT = "4321"
HOSTNAME = "0.0.0.0"

[phases.setup]
nixPkgs = ["nodejs_18"]
